### PR TITLE
Bugfixes and descriptions / tooltips for paymenttype statistics.

### PR DESCRIPTION
**Pull request by philip-n**
Bugfixes:
- Corrected display for Polish account
- Added correct conversions for calculation of total sum in EUR

Extensions:
- Added panel with currency conversion factors
- Added tooltips
- Extended some textual descriptions

### CODE REVIEW

**Comment by philip-n** [comment]
Will come back to the e-tickets in a couple of minutes.

For the payment types, opening [ers instance]/admin/payment-type/format/3 results in an 404 error (both on the live system and on my playground-installation, also for the other accounts 1 .. 5):

```
The requested controller was unable to dispatch the request.

Controller:
Admin\Controller\PaymentType
No Exception available
```

**Comment by philip-n** [comment]
Just looked into the e-ticket commit - modifications were not meant for the e-ticket, but for the according confirmation mail. Besides, all were successfully tested on my test installation.

**Comment by inbaz** [comment]
From where did you get to this format link? It's already the new one which is not implemented, yet. It should be the old link that's working with the new structure which ist: /admin/bankaccount/format/2.

**Comment by philip-n** [comment]
The link I tried to access was via Shop > payment type > add statement format. Did not look wrong as it lists very similar entries to the correct link ;)

**Pull request merged**
